% phage.cls
%
% A LaTeX2e document class for preparing textbooks

%%% Eric Rasche
%%% Center for Phage Technology
%%% Texas A&M University
%%% esr@tamu.edu


\def\fileversion{3.0}
\def\filedate{2015/01/19}

\ProvidesClass{phage3}[\filedate Textbook style ``Phage'' by Eric Rasche]
\LoadClass{memoir}
\input{common}
\input{common_memoir_extra}
\input{cls_thinkabout}
\input{cls_chapter}
\input{title_textbook}
\input{headings_quiet_rev}
%\setmainfont{EBGaramond12-Regular.ttf}

\input{common_end}
